version: '3.7'

services:
  db:
    image: mongo:4.2-bionic
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db

  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/app
    env_file:
      - .env
    depends_on:
      - db

volumes:
  dbdata:
